version: '3.7'
services:
  db-test:
    image: postgres:14-alpine
    container_name: db-test
    restart: always
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}test
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - '5454:5432'
    networks:
      - pcc-test
  backend-test:
    image: pcc-backend-test:latest
    container_name: pcc-backend-test
    restart: always
    build:
      context: '.'
      target: development
    stdin_open: true
    command: 'yarn run start:backend:test'
    ports:
      - '3100:3000'
    environment:
      - DB_HOST=db-test
      - DB_NAME=${DB_NAME}test
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_LOGS_ENABLED=${DB_LOGS_ENABLED}
      - MAIL_SERVICE_BASE_URL=${MAIL_SERVICE_BASE_URL}
      - MAIL_SERVICE_KEY=${MAIL_SERVICE_KEY}
      - MAIL_SERVICE_DEFAULT_TO_EMAIL=${MAIL_SERVICE_DEFAULT_TO_EMAIL}
      - AUTH_BASE_URL=${AUTH_BASE_URL}
      - CHOKIDAR_USEPOLLING=true
      - APP_PORT=3000
      - NODE_ENV=ci
      - RUNTIME_ENV=test
      - API_URL=${API_URL}
      - AWS_ACCESS_KEY_ID=pcc
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_DEFAULT_REGION=${AWS_REGION}
      - YARN_VERSION=3.2.3
      - AWS_ENDPOINT=http://minio:9000
    volumes:
      - ./apps/backend:/apps/backend
      - ./node_modules:/node_modules
    depends_on:
      - db-test
    networks:
      - pcc-test

  minio:
    image: minio/minio
    container_name: pcc-minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: pcc
      MINIO_ROOT_PASSWORD: password
    command: server --console-address ":9001" /data
    networks:
      - pcc-test

networks:
  pcc-test:
    driver: bridge
    name: pcc-test
volumes:
  minio_storage: {}
  pg_data: {}
