version: '3.7'
services:
  db:
    image: postgres:14-alpine
    container_name: pcc-db
    restart: always
    env_file: .env
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - pcc

  backend:
    image: pcc-backend:latest
    container_name: pcc-backend
    build:
      context: '.'
      target: development
    restart: unless-stopped
    stdin_open: true
    command: 'yarn start:backend:local'
    ports:
      - '3000:3000'
      - '8081:8080'
    environment:
      - APP_VERSION=${APP_VERSION}
      - API_VERSION=${API_VERSION}
      - SILENCE_LOGS=${SILENCE_LOGS}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_LOGS_ENABLED=${DB_LOGS_ENABLED}
      - MAIL_SERVICE_BASE_URL=${MAIL_SERVICE_BASE_URL}
      - MAIL_SERVICE_KEY=${MAIL_SERVICE_KEY}
      - MAIL_SERVICE_DEFAULT_TO_EMAIL=${MAIL_SERVICE_DEFAULT_TO_EMAIL}
      - SNS_RECONCILER_RESULTS_TOPIC=${SNS_RECONCILER_RESULTS_TOPIC}
      - SNS_PARSER_RESULTS_TOPIC=${SNS_PARSER_RESULTS_TOPIC}
      - AUTH_BASE_URL=${AUTH_BASE_URL}
      # watch for files changes within the container
      - CHOKIDAR_USEPOLLING=true
      - APP_PORT=3000
      - NODE_ENV=local
      - RUNTIME_ENV=local
      - API_URL=${API_URL}
      - AWS_ACCESS_KEY_ID=pcc
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_DEFAULT_REGION=${AWS_REGION}
      - YARN_VERSION=3.2.3
      - AWS_ENDPOINT=http://minio:9000
    volumes:
      - ./apps/backend:/apps/backend
      - ./node_modules:/node_modules
      - compodoc:/apps/backend/src/docs
    depends_on:
      - db
    networks:
      - pcc

  minio:
    image: minio/minio
    container_name: pcc-minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: pcc
      MINIO_ROOT_PASSWORD: password
    command: server --console-address ":9001" /data
    networks:
      - pcc
networks:
  pcc:
    driver: bridge
    name: pcc
volumes:
  minio_storage: {}
  pg_data: {}
  compodoc: {}
