version: "3.7"
services:
  backend:
    container_name: backend
    build: 
      context: './apps/backend'
    networks:
      - localstack-net
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING="true"
      - APP_PORT=3000
      - NODE_ENV=local
      - AWS_ACCESS_KEY_ID="test"
      - AWS_SECRET_ACCESS_KEY="test"
      - AWS_DEFAULT_REGION="ca-central-1"
      - YARN_VERSION=3.2.3
      - AWS_ENDPOINT=http://localstack:4566
    volumes:
      - ./apps/backend:/usr/arc/app
      - /usr/arc/app/node_modules
  localstack:
    container_name: localstack
    image: localstack/localstack-full:1.1.0
    networks:
      - localstack-net
    ports:
      - "4566-4599:4566-4599"
      - "8080:8080"
    environment:
      - SERVICES=kinesis,s3,sqs,lambda,iam,events
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack
      - PORT_WEB_UI=8080
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_REMOTE_DOCKER=false
      - LAMBDA_REMOVE_CONTAINERS=true
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - PERSISTENCE=1
    volumes:
      - ./.localstack:/var/lib/localstack
      - ./localstack/init/ready.d:/etc/localstack/init/ready.d
networks:
  localstack-net:
    external: false
    driver: bridge
    name: localstack-net
