version: "3.7"
services:
  db:
    image: postgres:14-alpine
    container_name: db
    restart: always
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=pcc
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_ROOT_PASSWORD=postgres
    ports:
      - "5454:5432"
    networks:
      - pcc-test
  backend:
    image: pcc-backend:latest
    container_name: pcc-backend
    restart: always
    build:
      context: "./apps/backend"
      target: development
    stdin_open: true
    command: 'yarn start:test'
    ports:
      - "3100:3000"
    environment:
      - DB_HOST=db
      - DB_NAME=bcpcc
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_ROOT_PASSWORD=postgres
      - ALLOWED_EMPTY_PASSWORD=yes
      - CHOKIDAR_USEPOLLING=true
      - APP_PORT=3000
      - NODE_ENV=test
      - RUNTIME_ENV=test
      - AWS_ACCESS_KEY_ID=pcc
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_DEFAULT_REGION=ca-central-1
      - YARN_VERSION=3.2.3
      - AWS_ENDPOINT=http://minio:9000
    volumes:
      - ./apps/backend:/usr/src/app
      - ./apps/backend/node_modules:/usr/src/app/node_modules
    depends_on:
      - db
    networks:
      - pcc-test

  minio:
    image: minio/minio
    container_name: pcc-minio
    ports:
      - "9100:9000"
      - "9101:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: pcc
      MINIO_ROOT_PASSWORD: password
    command: server --console-address ":9001" /data
    networks:
      - pcc-test

networks:
  pcc-test:
    driver: bridge
    name: pcc-test
volumes:
  minio_storage: {}
  pg_data: {}
