export enum MAIL_TEMPLATE_ENUM {
  FILES_MISSING_ALERT = 'FILES_MISSING_ALERT',
  FILE_VALIDATION_ALERT = 'FILE_VALIDATION_ALERT',
}

export const MailTemplate = {
  [MAIL_TEMPLATE_ENUM.FILES_MISSING_ALERT]: {
    id: '1b74858b-1ac9-4f9c-bd77-d3aea5116c73',
    name: MAIL_TEMPLATE_ENUM.FILES_MISSING_ALERT,
  },
  [MAIL_TEMPLATE_ENUM.FILE_VALIDATION_ALERT]: {
    id: '70210885-d584-4715-8e8b-60e945e46e67',
    name: MAIL_TEMPLATE_ENUM.FILE_VALIDATION_ALERT,
  },
};
