export const policies = {
  contentSecurityPolicy: {
    directives: {
      defaultSrc: [`'self'`],
      imgSrc: `'self' data:`,
      scriptSrc: [`'self'`],
      styleSrc: [
        `'self'`,
        `'sha256-/jDKvbQ8cdux+c5epDIqkjHbXDaIY8RucT1PmAe8FG4='`,
        `'sha256-ezdv1bOGcoOD7FKudKN0Y2Mb763O6qVtM8LT2mtanIU='`,
        `'sha256-eaPyLWVdqMc60xuz5bTp2yBRgVpQSoUggte1+40ONPU='`,
      ],
      fontSrc: [`'self'`],
    },
  },
  permissionsPolicy: `'accelerometer=()',
    'ambient-light-sensor=()',
    'autoplay=()',
    'battery=()',
    'camera=()',
    'cross-origin-isolated=()',
    'display-capture=()',
    'document-domain=()',
    'encrypted-media=()',
    'execution-while-not-rendered=()',
    'execution-while-out-of-viewport=()',
    'fullscreen=()',
    'geolocation=()',
    'gyroscope=()',
    'keyboard-map=()',
    'magnetometer=()',
    'microphone=()',
    'midi=()',
    'navigation-override=()',
    'payment=()',
    'picture-in-picture=()',
    'publickey-credentials-get=()',
    'screen-wake-lock=()',
    'sync-xhr=()',
    'usb=()',
    'web-share=()',
    'xr-spatial-tracking=()',
    'clipboard-read=()',
    'clipboard-write=()',
    'gamepad=()',
    'speaker-selection=()',
    'conversion-measurement=()',
    'focus-without-user-activation=()',
    'hid=()',
    'idle-detection=()',
    'interest-cohort=()',
    'serial=()',
    'sync-script=()',
    'trust-token-redemption=()',
    'unload=()',
    'window-placement=()',
    'vertical-scroll=()'`,
};
