name: Jira issue in PR title

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

jobs:
  check-pr-title-jira-link:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check PR title for Jira ticket number unless it is a CHORE/FIX/REFACTOR/DEVOPS PR
        uses: gsactions/commit-message-checker@8c8c0d18ba9b1fcfed6e7385fd2bf357dfc8dccb
        with:
          pattern: '(\W)+(CCFPCM)+-[0-9]+(\W)|(\W)(CHORE|FIX|REFACTOR|DEVOPS)(\W)'
          excludeTitle: "false" # optional: this excludes the title of a pull request
          excludeDescription: "true" # optional: this excludes the description body of a pull request
          checkAllCommitMessages: "false" # optional: this checks all commits associated with a pull request
          # accessToken: ${{ secrets.GITHUB_TOKEN }} # github access token is only required if checkAllCommitMessages is true
          error: "PR title should look like [CCFPCM-####] or [CHORE] or [FIX] or [REFACTOR] for general non feature commits"
