name: PR - Linting

on:
  workflow_dispatch:
  pull_request:
    paths:
      - apps/backend/**

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
        name: checkout

      - uses: actions/cache@v3
        name: Cache yarn
        with:
          path: ./.yarn/cache
          key: pcc-backend
          restore-keys: pcc-backend

      - uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: yarn

      - name: Lint Check
        run: yarn workspace @payment/backend lint