name: Tests pipeline

on:
  workflow_dispatch:
  pull_request:
    paths:
      - apps/backend/**
      - yarn.lock

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Cache yarn
        uses: actions/cache@v3
        with:
          path: ./.yarn/cache
          key: pcc-backend
          restore-keys: pcc-backend

      - uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build:backend

      - name: Setup ENV file
        run: cp ./.config/.env.example ./.env

      - name: Run Docker containers
        run: make build

      - name: Run migrations
        run: make migration-run-ci

      - name: Build and Run Test Container
        run: make run-test

      - name: Run Tests
        run: make run-test-pipeline

      - name: Stop containers
        run: make close-test
        if: ${{ always() }}
