name: Deployment - PROD
on:
  push:
    tags:
      - prod
env:
  ENV_NAME: prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency: ci-${{ github.ref }}-prod
    environment:
      name: prod-deployment
    steps:
      - uses: actions/checkout@v3
        name: checkout

      - uses: actions/cache@v3
        name: Cache yarn
        with:
          path: ./.yarn/cache
          key: pcc-backend-prod
          restore-keys: pcc-backend-prod

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-skip-session-tagging: true
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
          aws-region: ca-central-1
          role-to-assume: ${{ secrets.AWS_SA_ROLE_ARN }}
          role-duration-seconds: 900
          role-session-name: ci-prod-deployment

      - name: Install dependencies
        run: yarn

      - name: Setup ENV file
        run: cp ./.config/.env.example ./.env

      - name: Build
        run: make build-backend

      - name: Upload build artifacts
        run: make aws-upload-artifacts

      - name: Deploy Migrations
        run: make aws-deploy-migrator

      - name: Run Migrations
        run: make aws-run-migrator

      - name: Deploy All
        run: make aws-deploy-all
