name: DEV - Deploy Apps
on:
  push:
    tags:
      - dev
env:
  ENV_NAME: dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency: ci-${{ github.ref }}-dev
    environment:
      name: dev
    steps:
      - uses: actions/checkout@v3
        name: checkout

      - uses: actions/cache@v3
        name: Cache yarn
        with:
          path: ./.yarn/cache
          key: pcc-backend
          restore-keys: pcc-backend

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-skip-session-tagging: true
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
          aws-region: ca-central-1
          role-to-assume: ${{ secrets.AWS_SA_ROLE_ARN }}
          role-duration-seconds: 900
          role-session-name: ci-dev-deployment

      - name: Install dependencies
        run: yarn

      - name: Build
        run: make build

      - name: Deploy
        run: make deploy-backend
